export const initialValues = {
    email: '',
    firstName: '',
    lastName: '',
    middleName: '',
    nameExtension: '',
    birthDate: new Date(),
    rfid: '',
    mobileNumber: '',
    section: '',
    department: '',
    yearLevel: '',
    strand: '',
    course: '',
    isCollege: false,
};